name: Continuous Delivery

on:
  push:
    branches:
      - master #deploy to production branch
      - develop #deploy to develop branch

env:
  IMAGE_NAME: residex-java
  AZURE_WEBAPP_NAME: fiap-simple-dev
  SLOT_NAME: prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Setup Java SDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        environment: [dev, prod]
    steps:
      - name: Slot name based on environment
        run: |
          if [[ "${{ matrix.environment }}" == "dev" ]]; then
            echo "SLOT_NAME=dev" >> $GITHUB_ENV
          else
            echo "SLOT_NAME=production" >> $GITHUB_ENV
          fi
      - name: Show slot name
        run: echo "Deploy slot name $SLOT_NAME"

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: ${{ env.SLOT_NAME }}
          publish-profile: ${{ secrets.AZURE_PROFILE }}
          images: "index.docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest"
      - name: Print Web App URL
        run: |
          echo "Web App URL: ${{ steps.deploy-to-webapp.outputs.webapp-url }}"
          curl -I ${{ steps.deploy-to-webapp.outputs.webapp-url }} || exit 1
