name: Continuous Delivery

on:
  push:
    branches:
      - master # Deploy para produção
      - develop # Deploy para desenvolvimento

env:
  IMAGE_NAME: residex-java
  AZURE_WEBAPP_NAME_DEV: fiap-simple-dev
  AZURE_WEBAPP_NAME_PRD: fiap-simple-prd

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Setup Java SDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Profile Based on Branch
        id: set-profile
        run: |
          if [[ "${GITHUB_REF_NAME}" == "master" ]]; then
            echo "PROFILE=prd" >> $GITHUB_ENV
          else
            echo "PROFILE=dev" >> $GITHUB_ENV
          fi

      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}-latest
          build-args: |
            PROFILE=${{ env.PROFILE }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set Variables Based on Branch
        id: set-variables
        run: |
          if [[ "${GITHUB_REF_NAME}" == "master" ]]; then
            echo "APP_NAME=${{ env.AZURE_WEBAPP_NAME_PRD }}" >> $GITHUB_ENV
            echo "PUBLISH_PROFILE=${{ secrets.AZURE_PROFILE_PRD }}" >> $GITHUB_ENV
          else
            echo "APP_NAME=${{ env.AZURE_WEBAPP_NAME_DEV }}" >> $GITHUB_ENV
            echo "PUBLISH_PROFILE=${{ secrets.AZURE_PROFILE }}" >> $GITHUB_ENV
          fi

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_NAME }}
          publish-profile: ${{ secrets.PUBLISH_PROFILE }}
          images: "index.docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}-latest"
